name: Metadata collector

on:
  workflow_call:
    outputs:
      charts:
        description: "List of charts within the repository"
        value: ${{ jobs.chart-list.outputs.charts }}

permissions:
  contents: read

jobs:
  chart-list:
    runs-on: ubuntu-24.04
    outputs:
      charts: ${{ steps.charts.outputs.charts }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 # pragma: allowlist secret
        with:
          persist-credentials: false

      - name: Get changed files
        uses: step-security/changed-files@95b56dadb92a30ca9036f16423fd3c088a71ee94 # v46.0.5
        id: changed-directories
        with:
          dir_names: "true"
          dir_names_max_depth: "1"
          path: charts
          matrix: "true"

      - name: Collect charts
        id: charts
        run: echo "charts=$(echo "${CHANGED_CHART_DIRS//charts\//}" | tr -d '\n' | jq -R -s -c 'split(" ")')" >> "$GITHUB_OUTPUT"
        env:
          CHANGED_CHART_DIRS: ${{ steps.changed-directories.outputs.all_changed_files }}
